### ISSUE TITLE
Transport Security check error for Collectives

### ISSUE THREAD

**Issue by jdryden-osi** [osisoft/PI-Security-Audit-Tools#256]
In Test-PISysAudit_SecurePIConnections

Connection messages for pibasess between PI Collective members use the method of "HACertifiedSubsys". When searching this string for open and close parentheses, it will fail which then causes the Substring() method to fail.

This Substring call should be performed after a check to ensure the index is valid, to avoid an exception. 

~~Connections between collective members should be considered secure~~ (see below reply). This connection message may be different in Data Archive 2017, so this should be checked as well.

**Comment by gavchen** [comment]
Collective member connections prior to PI Data Archive 2017 are actually not secured with transport security, despite the apparent use of a certificate. Transport security for collective members was introduced in 2017.

**Comment by jdryden-osi** [comment]
Thanks @gavchen , given that info I take back my last assertion on the issue statement. We will have to further discuss how to classify Collective connections on versions prior to 2017. Should Collective sync connections be ignored for the Transport Security check? Or should we flag them with a recommendation to upgrade (in addition to the PI Data Archive version check)? Perhaps we could flag it with a reduced severity if this is the only connection in violation?
