### ISSUE TITLE
Extend Kerberos configuration check to support PI Web API

### ISSUE THREAD

**Issue by hpaul-osi** [osisoft/PI-Security-Audit-Tools#258]
Presently, the Kerberos configuration utility only supports checking the configuration of PI Vision which is tied to the site installed in IIS.  The tool needs to be generalized to support PI Web API which is self-hosted.  When implementing support for PI Web API, we should consider how the changes can facilitate adding other applications with minimal inertia.

**Comment by LubosOSI** [comment]
I've been working on generalizing the tool in the last few weeks, so I am assigning this item to myself.

**Comment by LubosOSI** [comment]
Closing.
