### ISSUE TITLE
Add PI Coresight validation: require SSL

### ISSUE THREAD

**Issue by hpaul-osi** [osisoft/PI-Security-Audit-Tools#30]
Add the following validation check for PI Coresight, (AU5XXXXX):

Validation: verify the PI Coresight web site requires SSL
Compliance: a valid https binding should be configured and only connections with SSL should be allowed. 

Note: StartPICoresightServerAudit already checks for availability of Web-Scripting-Tools server feature.  The WebAdministration module should be used if available.

**Comment by LubosOSI** [comment]
SSL check is now done on Web App and Web Site level. Basic Auth is considered. Closing.
