### ISSUE TITLE
Add PI Coresight validation: trusted authority certificate

### ISSUE THREAD

**Issue by hpaul-osi** [osisoft/PI-Security-Audit-Tools#35]
Add the following validation check for PI Coresight, (AU5XXXXX):

Validation: verify the PI Coresight application is using a certificate from a trusted authority.
Compliance: PI Coresight should not be using a self-signed certificate.

**Comment by LubosOSI** [comment]
SSL issuer is now checked (assuming all other SSL checks pass).
