### ISSUE TITLE
Improve System/App Hotfix/Update check

### ISSUE THREAD

**Issue by LubosOSI** [osisoft/PI-Security-Audit-Tools#379]
The current Hotfix/App update check implementation relies on InstalledOn property. However, on some systems, hotfixes/app updates are deployed in such a way that the property is unavailable, resulting in incorrect report output (false positives).

A more reliable way should be implemented. Checking registry key time stamps could be one of the alternatives.

**Comment by hpaul-osi** [comment]
Only affects systems with custom implementation.
