### ISSUE TITLE
Add PI Coresight validation: SPN check

### ISSUE THREAD

**Issue by LubosOSI** [osisoft/PI-Security-Audit-Tools#46]
1. Get information about bindings of Coresight Web Site and Coresight AppPools
2. Do SPN check

**Comment by FlorisAtMagion** [comment]
Would be nice if it would also check if 'Resource Based Constrained Delegation' is used in Windows Server 2012 R2 environment, in stead of SPN. Now it gives me a 'moderate' Severity on missing SPN.

**Comment by LubosOSI** [comment]
Currently we check only for existence of the SPN to verify whether Kerberos authentication to Coresight is possible. Kerberos Delegation check could be added of course, but then we should check for any delegation type, not just resource-based delegation.

**Comment by LubosOSI** [comment]
Support for custom headers has been added. Closing this one.
