### ISSUE TITLE
AU20009 - Check PI Server SPN

### ISSUE THREAD

**Issue by FlorisAtMagion** [osisoft/PI-Security-Audit-Tools#62]
I think there is a little misunderstanding here.
The check should be on the SPN on the AF server service account.(the link to the live library tells that it is about AF also)
The SPN for the PI Data Archive is automatically created when the PI server is started. By default on the machine account when the PI server service(PI base subsystem)(and Pi Network Manager) are run under the 'Local System' account.
I have not seen any documentation to run these services under a specific (domain)service account.

**Comment by LubosOSI** [comment]
The AFSERVER check is done for the AF Service account.
The PISERVER check is future-proof for when we add the option to run PI Services under custom service accounts. So we get identity of pinetmgr (which is LocalSystem now) and list the SPNs.
Automatic SPN creation by PI/AF might fail, depending on how the permission is set up, which is why we do the check.

**Comment by FlorisAtMagion** [comment]
Ok, clear.
I was referring to the text in the about_PISYSAUDIT.help.txt file under 'AU20009 - Check PI Server SPN'.
"VALIDATION: Checks PI Data Archive SPN assignment.
COMPLIANCE: PI Data Archive SPNs exist and are assigned to the pinetmgr Service account. 
This makes Kerberos Authentication possible.  For more information, see "PI and Kerberos 
authentication" in the PI Live Library. 
https://livelibrary.osisoft.com/LiveLibrary/content/en/server-v7/GUID-531FFEC4-9BBB-4CA0-9CE7-7434B21EA06D"

And to the line in the HTML audit Summary which states:
The Service Principal Name does NOT exist or is NOT assigned to the correct Service Account.

So this error is just for future use!?

**Comment by LubosOSI** [comment]
In this case, pinetmgr Service Account is LocalSystem (i.e. the machine identity), so it's actually correct.
I suppose we could change the text in output to explicitly state machine identity until we actually officially support using custom service accounts.

**Comment by hpaul-osi** [comment]
Clarified description in AU20009 to remove ambiguity about custom service accounts.
