### ISSUE TITLE
AU10005 UAC Enabled

### ISSUE THREAD

**Issue by FlorisAtMagion** [osisoft/PI-Security-Audit-Tools#63]
For some reason it keeps complaining about the 'ConsentPromptBehaviorAdmin' setting.
The options for this policy are:
-Automatically deny elevations requests
-Prompt for credentials on the secure desktop
-Prompt for credentials(default)

But either of these settings will result in a warning. 
Could it be that the check is looking for 'enabled/disabled'?

**Answer/correction:**
The options mentioned above are NOT for 'ConsentPromptBehaviorAdmin', but for ConsentPromptBehaviorUser. The check in AU10005 does not involve ConsentPromptBehaviorUser, but only ConsentPromptBehaviorAdmin.

**Comment by hpaul-osi** [comment]
The mappings for the registry key values are in this [article](https://technet.microsoft.com/en-us/library/dd835564(v=ws.10).aspx#BKMK_RegistryKeys).  A value of 0 for ConsentPromptBehaviorAdmin on the key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System corresponds to "Elevate without prompting" which is essentially disabled.

In PISYSAUDITCHECKLIB1 the function Get-PISysAudit_CheckUACEnabled loops through several UAC settings and makes sure they are not set to 0 (disabled).

```
$defaultEnabledUACFeatures = "EnableLUA", "ConsentPromptBehaviorAdmin", "EnableInstallerDetection", "PromptOnSecureDesktop", "EnableSecureUIAPaths"
		
		# Loop through key default enabled UAC features
		$tmpmsg = "Some default UAC features are disabled: "
foreach ($uacFeature in $defaultEnabledUACFeatures) 
		{
			if ($(Get-PISysAudit_RegistryKeyValue -lc $LocalComputer -rcn $RemoteComputerName -dbgl $DBGLevel -RegKeyPath $uacKeyPath -Attribute $uacFeature) -eq 0)
			{
				$result = $false
				$severity = "Moderate"
				$tmpmsg += $uacFeature + "; "
			}
		}
```

It is possible that the registry key value is not being read properly by the script, though I would expect that this would affect all of the values read for this particular check if that were the case.  Can you verify the value of the key using the PowerShell command below?
```
Get-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System -Name ConsentPromptBehaviorAdmin
```

**Comment by FlorisAtMagion** [comment]
Dear,
I checked the value with PowerShell and it is '0'.
My mistake. The value options I mentioned above are for the ConsentPromptBehaviorUser and not for ConsentPromptBehaviorAdmin.

**Comment by hpaul-osi** [comment]
OK, that explains it.  Thanks for the follow up.  I'll close this issue since the tool is behaving as expected.
