### ISSUE TITLE
Document the permissions needed by the security audit tools

### ISSUE THREAD

**Issue by gavchen** [osisoft/PI-Security-Audit-Tools#73]
What are the least required permissions needed for the security audit tools to run? For example, does it need certain permissions with Windows, PI Data Archive, PI AF, etc to run its audit checks?

**Comment by hpaul-osi** [comment]
**PI Data Archive:** _Read_ access to PIDBSEC, PIMAPPING, PITRUST, PIUSER and PITUNING.

**Comment by hpaul-osi** [comment]
Addressed with wiki page: [Required Permissions and Modules](https://github.com/osisoft/PI-Security-Audit-Tools/wiki/Required-Permissions-and-Modules)
