### ISSUE TITLE
Join-Path fails when the referenced drive is not available locally

### ISSUE THREAD

**Issue by LubosOSI** [osisoft/PI-Security-Audit-Tools#82]
This issue was reported in the PI Security Tools PI Square thread:
https://pisquare.osisoft.com/groups/security/blog/2016/07/26/check-out-the-pi-security-audit-tools-on-github?comment-7114=#comment-7112

We should be able to use standard string concatenation instead.

**Comment by hpaul-osi** [comment]
Addressed in #88
